### ISSUE TITLE
Chrome based browsers failing wss connection

### ISSUE THREAD

**Issue by lathanbritz** [XRPL-Labs/xrpl-client#16]
I tried the more complex version here, but event the simply array of wss as the constructor as the argument experiences this issue.
<img width="528" alt="Screenshot 2023-11-21 at 10 23 43" src="https://github.com/XRPL-Labs/xrpl-client/assets/508629/ae5d6c97-93c7-47cb-b087-2bb38520ecb7">

<img width="624" alt="Screenshot 2023-11-21 at 10 22 56" src="https://github.com/XRPL-Labs/xrpl-client/assets/508629/9c25a2b4-377a-4049-be00-03f4e873cf60">

connect via safari and no issue..

here is the source code https://github.com/lathanbritz/XRPL-Technical-Explorer/blob/ca048a235c8a11732763e7814ba8bc301662676f/src/store/app_store.js#L100

**Comment by WietseWind** [comment]
I'm afraid that's a Chrome problem, maybe a browser extension / ..
