### ISSUE TITLE
Faucet function

### ISSUE THREAD

**Issue by lathanbritz** [XRPL-Labs/xrpl-client#7]
Probably the most wanted feature i miss from this lib is a faucet function like that in xrpl.js

Having a function the same as that provided in the xrplf lib would be tremendously helpful.

**Comment by WietseWind** [comment]
I feel this doesn't belong in a client. `xrpl-client` is just that: a somewhat clever XRPL client. Faucets are a testnet thing, production code shouldn't be bloated by Faucet routines: I feel that belongs in a separate lib. 

A lib. like that has been made by another community member:
https://github.com/thebettermint/xrpl-auto-funder
