### ISSUE TITLE
The client will give up after one try when using tryAllNodes 

### ISSUE THREAD

**Issue by ckniffen** [XRPL-Labs/xrpl-client#9]
If all endpoints fail to get a connection when using `tryAllNodes` it will not try a second time.  This occasionally happens in the Explorer when a cluster is under high congestion.

## Steps to Reproduce

1. Call new new
```
  XrplClient(['wss://google.com', 'wss://yahoo.com'], {
    tryAllNodes: true
  })
```
3. Look at browser network tab you will see it gives up trying to make a connection.  Once per endpoint.
4. Set `tryAllNodes` to `false`
3. Look at browser network tab you will see it will keep trying to connect.

**Comment by WietseWind** [comment]
That's currently as designed (try all, or fail) but it's not too hard to add retrying anyway. Will work on that.

**Comment by WietseWind** [comment]
Added in `xrpl-client@2.0.2`, published.

https://github.com/XRPL-Labs/xrpl-client/commit/ec887f472845869839d62222529fdbd84b7984b8

**Comment by ckniffen** [comment]
Fantastic!
